modLoader="javafml"
loaderVersion="[26,)"
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/PackingTape/issues"
displayURL="https://github.com/gigaherz/PackingTape"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[mods]]
modId="packingtape"
version="${file.jarVersion}"
displayName="Packing Tape"
description='''
Adds a simple means to carry thigns with you
'''

[[dependencies.packingtape]]
    modId="forge"
    mandatory=true
    versionRange="[26.0.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.packingtape]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2,1.15)"
    ordering="NONE"
    side="BOTH"