modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
#updateJSONURL="http://myurl.me/" #optional
issueTrackerURL="https://github.com/gigaherz/PackingTape/issues" #optional
displayURL="https://github.com/gigaherz/PackingTape" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional

[[mods]] #mandatory
modId="packingtape" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Packing Tape" #mandatory
description='''
Adds a simple means to carry thigns with you
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[15.25.0.26,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.14)"
    ordering="NONE"
    side="BOTH"